export const SET_DEPARTURE_HUB = "SET_DEPARTURE_HUB";
export const SET_DESTINATION = "SET_DESTINATION ";
export const SET_OUTBOUNG_DATE = "SET_OUTBOUNG_DATE";
export const SET_RETURN_DATE = "SET_RETURN_DAT ";
export const SET_PASSENGER_NO = "SET_PASSENGER_NO";
export const SET_FLEXIBLE_NUMBER = "SET_FLEXIBLE_NUMBER";

export const SET_PARTIAL_HUBS = "SET_PARTIAL_HUBS";
